permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
pygments: true

# 作者信息
author: 
  name: fantaster
  email: arrowylq@foxmail.com
  link: http://杨柳青一些事.中国
  weibo: http://weibo.com/orangeissweet
  github: http://github.com/lay1010
  music: http://site.douban.com/linanya
  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: fantaster | 杨柳青
description: My personal blog
url: http://杨柳青一些事.中国
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: liuqingyang

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX
  - lalala
# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档