permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
pygments: true

# 作者信息
author: 
  name: fantaster
  email: arrowylq@outlook.com
  link: http://www.leesins.xyz/
  weibo: http://weibo.com/
  github: http://github.com/
  music: http://site.douban.com/
  linkedin: https://www.linkedin.com/

# 站点信息
# title: fantaster | 杨柳青
title: Arrow的代码之路
description: My personal blog
url: http://www.leesins.xyz/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/cat.png
favicon: /public/img/smallcat.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: fantaster

# 主题设置，自动激活某个标签
active: linux

# 首页除了最新文章外显示分类
cates: 
  - Linux
# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
